### ISSUE TITLE
Drupal integration

### ISSUE THREAD

**Issue by devekko** [maschmann/php-ansible#12]
hi

any thoughts on integration with Drupal 8 ?

am looking at using this Drupal 8 contrib module as a stepping stone

https://github.com/ergonlogic/ran

thannks

**Comment by maschmann** [comment]
Hi,
I'm not planning to build a Drupal module - and I'm not familiar with module guidelines, so I can't really give you any input on this. The repository you've linked, already uses ansible and vagrant; I don't see a usecase for php-ansible there :-(
