### ISSUE TITLE
Bug in createProcess()

### ISSUE THREAD

**Issue by gemini1389** [maschmann/php-ansible#17]
I think that the method createProcess() has a bug. It sends an object ProcessBuilder() the default timeout value.
https://github.com/maschmann/php-ansible/blob/master/Ansible/Ansible.php#L117

It should look like this:
```php
private function createProcess($prefix)
{
    $process = new ProcessBuilder();
    return $process
        ->setPrefix($prefix)
        ->setWorkingDirectory($this->ansibleBaseDir)
        ->setTimeout($this->timeout);
}
```

P.S. Sorry for using the Google Translate :)

**Comment by xabbuh** [comment]
I think you are right (see #18).
