### ISSUE TITLE
symfony/process requirement conflict with Laravel 5.2

### ISSUE THREAD

**Issue by saverio** [maschmann/php-ansible#26]
Larval 5.2.x requires 3.0.7; however php-ansible is specifically looking for symfony/process ~2.6. This is causing composer to bail out when trying to install composer on my Laravel project. 

Is there any chance php-ansible can upgrade to use symfony/process 3.x to resolve the conflict?

**Comment by xabbuh** [comment]
@saverio You can use the dev version (such a fix was merged in #20).

**Comment by saverio** [comment]
Awesome...any reason that hasn't been tagged yet? Any concerns you have?

**Comment by xabbuh** [comment]
ping @maschmann :)

**Comment by maschmann** [comment]
I think the only reason was Mr. maschmann not having time to do so (yet).
Will be done.

**Comment by maschmann** [comment]
done
