### ISSUE TITLE
Process class is not properly referenced

### ISSUE THREAD

**Issue by saverio** [maschmann/php-ansible#29]
When embedded within another namespaced class, the Ansible class fails to initiate because it can't find "Process" within that namespace, this is because an explicit reference to Symfony's Process class isn't provided.

**Comment by maschmann** [comment]
I'll add this to master and in the next few days will tag a 1.x final version with support for ansible 1.x and then begin integrating ansible 2.x :-)
Thanks for the contribution! :+1:
