### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'Ansible' not found

### ISSUE THREAD

**Issue by jtommi** [maschmann/php-ansible#38]
Hi,
I'm pretty new to composer and ansible and am pretty sure that the issue I'm experiencing is due to my lack of knowledge.

I followed the steps in the readme, but my apache2 error.log says "PHP Fatal error:  Uncaught Error: Class 'Ansible' not found". So I guess composer doesn't load stuff correctly.

My composer.json :
```
{
    "require": {
        "asm/php-ansible":"1.1.0"
    }
}
```

My ansible.php
```
     function select() {
        require 'vendor/autoload.php';
        echo "The select function is called.";
        $ansible = new Ansible(
            '/var/www/html/ansible-test'
        );
        $ansible
            ->playbook()
            ->play('testplay.yml') // based on deployment root
            ->inventoryFile('testplay')
            ->user('pi')
            ->execute(function ($type, $buffer) {
                if (Process::ERR === $type) {
                    echo 'ERR > '.$buffer;
                } else {
                    echo 'OUT > '.$buffer;
                }
            });
        exit;
    }
```

Can someone help me in the right direction ?

**Comment by adragos** [comment]
@jtommi did you by any chance also specified the `namespace` of the `Ansible` class?

**Comment by jtommi** [comment]
1. The composer.json contains only what I posted higher.
2. I'm using nothing like this, it's just a php page that handles a POST request

The idea of the project is to have a webpage with a button, pressing that button uses Ansible to send "shutdown +1" with the shell module to about 100 RPis

**Comment by xabbuh** [comment]
Can you create an example application that allows to reproduce your issue?

**Comment by adragos** [comment]
@jtommi you have, first of all an autoloading problem, which is unrelated to this project. The PHP processor can't find the class `Ansible` because it doesn't know where to look for it. 
If you look inside the `Ansible` class, you will see that it is located inside a namespace called `Asm\Ansible`, but your code is neither using a `use Asm\Ansible\Ansible`, nor instantiating the class using the FQCN.

**Comment by jtommi** [comment]
Thank you for your help in pointing me in the right direction.
I got it working in commandline; with a POST it's still a bit tricky, but I get output, the rest is just managing permissions of www-data, etc.

I think I even found a bug:
In Ansible.php on line 130 :
```if (true === shell_exec('which ' . $default))```
I had to change the === to ==, which makes sense since true is a boolean and shell_exec returns a string, so the condition was never met.


Here is my working example (executed in the commandline):
```
<?php

require_once 'vendor/autoload.php';
use Asm\Ansible\Ansible;
use Symfony\Component\Process\Process;

echo "It runs.";
$ansible = new Ansible(
	'/var/www/html/ansible-php'
);

$ansible
	->playbook()
	->play('testplay.yml') // based on deployment root 
	->inventoryFile('testplay')
	->user('pi')
	->execute(function ($type, $buffer) {
		if (Process::ERR === $type) {
			echo 'ERR > '.$buffer;
		} else {
			echo 'OUT > '.$buffer;
		}
	});
?>

```
And here my composer.json :
```
{
    "require": {
        "asm/php-ansible":"1.1.0"
    },
    "autoload": {
		"classmap": ["vendor"]
    }
}
```

**Comment by jtommi** [comment]
I see the bug was already fixed, it's just that on packagist it's an older version where the bug still exists : https://packagist.org/packages/asm/php-ansible
