### ISSUE TITLE
Invoked command cannot execute

### ISSUE THREAD

**Issue by paveldanilin** [maschmann/php-ansible#43]
Hi!
It seems there is a problem with a loss of command name in ProcessBuilder.

This code leads to an error "Invoked command cannot execute" 
```
$a = new Ansible('ansible/project/test', '/usr/bin/ansible-playbook');
$a->playbook()->play('playbook.yml')->execute();
```

I guess the cause is an overriding of $arguments array in ProcessBuilder class.

1. when we call Ansible::playbook(), there is a creation of AnsiblePlaybook instance that accepts as argument an instance of ProcessBuilder and we pass into constructor the playbookCommand
```
    public function playbook(): AnsiblePlaybookInterface
    {
        return new AnsiblePlaybook(
            $this->createProcess($this->playbookCommand)
        );
    }

```
2. Now we have ProcessBuilder::arguments[0] = '/usr/bin/ansible-playbook';
3. The overriding happens when we call AnsiblePlaybook::execute() , it calls protected method AbstractAnsibleCommand::runProcess:
```
  $process = $this->processBuilder
            ->setArguments(
                $this->prepareArguments()
            )
            ->getProcess();
```
The prepareArguments method does not take into consideration that ProcessBuilder::arguments[0]  already holds the value of command and spoils it.

In order to avoid a loss of command name, the ProcessBuilder::setArgument method should be changed to 
```
    public function setArguments(array $arguments): ProcessBuilderInterface
    {
        $prefix = $this->arguments[0] ?? null;

        if ($prefix !== null) {
            $this->arguments = array_merge([$prefix], $arguments);
        } else {
            $this->arguments = $arguments;
        }

        return $this;
    }
```

**Comment by maschmann** [comment]
Hi @paveldanilin 

thanks for the report! I'll have a look at the problem and get back to you shortly :-)

Kind regards,
Marc

**Comment by paveldanilin** [comment]
Hi, Marc!

Forgot to mention that all i wrote is related to 2.X version.

And thanks for your library it's extremely convenient to call ansible from
PHP app !

Regards,
Pavel

пн, 4 февр. 2019 г. в 22:51, Marc Aschmann <notifications@github.com>:

**Comment by paveldanilin** [comment]
Hello Marc,
Yes, now it works!

**Comment by maschmann** [comment]
Will be released soon :-)
