### ISSUE TITLE
Installation problem 

### ISSUE THREAD

**Issue by mlg1** [maschmann/php-ansible#46]
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove symfony/process v5.0.5
    - Conclusion: don't install laravel/framework v7.1.0
    - Conclusion: don't install laravel/framework v7.0.8
    - Conclusion: remove laravel/framework v7.0.7
    - Conclusion: don't install laravel/framework v7.0.7
    - Conclusion: don't install laravel/framework v7.0.6
    - Conclusion: don't install laravel/framework v7.0.5
    - Conclusion: don't install laravel/framework v7.0.4
    - Conclusion: don't install laravel/framework v7.0.3
    - Conclusion: don't install laravel/framework v7.0.2
    - Conclusion: don't install laravel/framework v7.0.1
    - Conclusion: don't install laravel/framework v7.0.0
    - Conclusion: don't install symfony/process v5.0.5
    - Conclusion: don't install symfony/process v4.4.5|install symfony/process v5.0.5
    - Conclusion: don't install symfony/process v5.0.4|install symfony/process v4.4.5
    - Conclusion: don't install symfony/process 5.1.x-dev|install symfony/process v4.4.5
    - Conclusion: don't install symfony/process v5.0.0-BETA1|install symfony/process v4.4.5
    - Installation request for laravel/framework ^7.0 -> satisfiable by laravel/framework[7.x-dev, v7.0.0, v7.0.1, v7.0.2, v7.0.3, v7.0.4, v7.0.5, v7.0.6, v7.0.7, v7.0.8, v7.1.0].
    - Conclusion: don't install symfony/process v4.4.4
    - Conclusion: don't install symfony/process v5.0.0-BETA2|install symfony/process v4.4.4|install symfony/process v4.4.5
    - Conclusion: don't install symfony/process v5.0.0-RC1|install symfony/process v4.4.4|install symfony/process v4.4.5
    - Conclusion: don't install symfony/process v5.0.0|install symfony/process v4.4.4|install symfony/process v4.4.5
    - Conclusion: don't install symfony/process v5.0.1|install symfony/process v4.4.4|install symfony/process v4.4.5
    - Installation request for asm/php-ansible master -> satisfiable by asm/php-ansible[dev-master].
    - Conclusion: don't install symfony/process v5.0.2|install symfony/process v4.4.4|install symfony/process v4.4.5
    - asm/php-ansible dev-master requires symfony/process ^4.0 -> satisfiable by symfony/process[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.2, v4.4.3, v4.4.4, v4.4.5].
    - Can only install one of: symfony/process[5.0.x-dev, 4.0.x-dev].
    - Can only install one of: symfony/process[5.0.x-dev, 4.1.x-dev].
    - Can only install one of: symfony/process[5.0.x-dev, 4.2.x-dev].
    - Can only install one of: symfony/process[5.0.x-dev, 4.3.x-dev].
    - Can only install one of: symfony/process[5.0.x-dev, 4.4.x-dev].
    - Can only install one of: symfony/process[v4.0.0, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.0-BETA1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.0-BETA2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.0-BETA3, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.0-BETA4, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.0-RC1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.0-RC2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.10, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.11, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.12, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.13, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.14, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.15, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.3, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.4, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.5, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.6, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.7, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.8, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.0.9, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.0, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.0-BETA1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.0-BETA2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.0-BETA3, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.10, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.11, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.12, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.3, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.4, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.5, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.6, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.7, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.8, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.1.9, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.0, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.0-BETA1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.0-BETA2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.0-RC1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.10, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.11, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.12, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.3, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.4, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.5, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.6, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.7, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.8, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.2.9, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.0, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.0-BETA1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.0-BETA2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.0-RC1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.10, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.11, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.3, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.4, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.5, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.6, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.7, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.8, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.3.9, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.4.0, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.4.0-BETA1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.4.0-BETA2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.4.0-RC1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.4.1, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.4.2, 5.0.x-dev].
    - Can only install one of: symfony/process[v4.4.3, 5.0.x-dev].
    - laravel/framework 7.x-dev requires symfony/process ^5.0 -> satisfiable by symfony/process[v5.0.5, 5.0.x-dev, 5.1.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.2, v5.0.3, v5.0.4].
    - Conclusion: don't install symfony/process v5.0.3|install symfony/process v4.4.4|install symfony/process v4.4.5

**Comment by xabbuh** [comment]
#47 should fix this

**Comment by mlg1** [comment]
Thank you very much! The installation is now successful.
