### ISSUE TITLE
can't install with symfony/console

### ISSUE THREAD

**Issue by Djomobil** [maschmann/php-ansible#49]
Can you update the composer.json ?

composer require asm/php-ansible
Using version ^2.0 for asm/php-ansible
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install asm/php-ansible v2.0.0
    - Conclusion: don't install asm/php-ansible v2.0.1-alpha
    - Conclusion: remove symfony/console v5.0.7
    - Conclusion: don't install symfony/console v5.0.7

**Comment by maschmann** [comment]
Hi @Djomobil 
I've updated to the latest process component - this is currently on dev. I'll still have to verify the package still working.
