### ISSUE TITLE
symfoney/process version conflict

### ISSUE THREAD

**Issue by goatatwork** [maschmann/php-ansible#6]
I am attempting to use php-ansible in a Laravel 5.1 project.  Laravel requires symfony/process v2.7.1 while php-ansible requires symfony/process ~2.6.0.

Output:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for asm/php-ansible dev-master -> satisfiable by asm/php-ansible[dev-master].
    - Conclusion: remove symfony/process v2.7.1
    - Conclusion: don't install symfony/process v2.7.1
    - asm/php-ansible dev-master requires symfony/process ~2.6.0 -> satisfiable by symfony/process[2.6.x-dev, v2.6.0, v2.6.0-BETA1, v2.6.0-BETA2, v2.6.1, v2.6.10, v2.6.11, v2.6.2, v2.6.3, v2.6.4, v2.6.5, v2.6.6, v2.6.7, v2.6.8, v2.6.9].
    - Can only install one of: symfony/process[2.6.x-dev, v2.7.1].
    - Can only install one of: symfony/process[v2.6.0, v2.7.1].
    - Can only install one of: symfony/process[v2.6.0-BETA1, v2.7.1].
    - Can only install one of: symfony/process[v2.6.0-BETA2, v2.7.1].
    - Can only install one of: symfony/process[v2.6.1, v2.7.1].
    - Can only install one of: symfony/process[v2.6.10, v2.7.1].
    - Can only install one of: symfony/process[v2.6.11, v2.7.1].
    - Can only install one of: symfony/process[v2.6.2, v2.7.1].
    - Can only install one of: symfony/process[v2.6.3, v2.7.1].
    - Can only install one of: symfony/process[v2.6.4, v2.7.1].
    - Can only install one of: symfony/process[v2.6.5, v2.7.1].
    - Can only install one of: symfony/process[v2.6.6, v2.7.1].
    - Can only install one of: symfony/process[v2.6.7, v2.7.1].
    - Can only install one of: symfony/process[v2.6.8, v2.7.1].
    - Can only install one of: symfony/process[v2.6.9, v2.7.1].
    - Installation request for symfony/process == 2.7.1.0 -> satisfiable by symfony/process[v2.7.1].

**Comment by maschmann** [comment]
Hi @goatatwork! This has to do with my minimum version requirement of symfony. Since laravel uses older dependencies there's a mismatch in versions.
I'll implement some tests to check if the older versions of symfony (components) also work and then reduce the minimal requirements.

**Comment by goatatwork** [comment]
Wow, you win today @maschmann.  Thank you so much.  When I land tonight, I'll give this a shot!

**Comment by goatatwork** [comment]
Just ran 'composer require asm/php-ansible' and all is well.  Thank you again @maschmann.

**Comment by maschmann** [comment]
no problem :+1:  I'll add more testing to travis then and check how far the component version support goes
