### ISSUE TITLE
[Help] How do I know if an ansible run was successfull or not?

### ISSUE THREAD

**Issue by ppshobi** [maschmann/php-ansible#63]
I have the following code
```
 $result = $ansible
            ->playbook()
            ->play($this->getPlaybookFilePath())
            ->inventoryFile($this->getHostsFilePath())
            ->execute(function ($type, $buffer) {
                if (Process::ERR === $type) {
                    file_put_contents($this->getLogFileName(),$buffer, FILE_APPEND);
                    echo $buffer;
                } else {
                    file_put_contents($this->getLogFileName(),$buffer, FILE_APPEND);
                    echo $buffer;
                }
            });
```

Is there any way to know that if the run was successful or not? from the `$result` variable or by some other means?

**Comment by maschmann** [comment]
Hi :-)
short: The $result is a process result variable and contains the exit state. 

> Every Linux command executed by the shell script or user, has an exit status. The exit status is an integer number. The Linux man pages stats the exit statuses of each command. 0 exit status means the command was successful without any errors.   

This means, you can check
`if (1 === $result) { 
    echo 'some error occured';
}
`
If there's an error, you can also consult the logs or get the buffer and show a commandline result. It's this way, so you can run this e.g. as a background command and won't clutter your console with output.

**Comment by ppshobi** [comment]
Thank you, I think I can close this issue.
