### ISSUE TITLE
psr/log version

### ISSUE THREAD

**Issue by donnyxray** [maschmann/php-ansible#81]
Please consider using  "^1.1|^2|^3" for psr/log.

Requiring 1.1 specifically conflicts with other packages that have moved on to requiring 2.x or newer.

**Comment by maschmann** [comment]
Hi, thanks for the info and taking your time, creating the issue!
I'll have a look if the interface is still compatible with my current implementation and add the additional versions accordingly. Not sure how current my other deps are - will check them, too :-)

**Comment by RoussKS** [comment]
@donnyxray @maschmann made a PR #83 as we use the library for an internal project based on Laravel. v10 has a chain requirement of `psr/log` v2 or v3 via the monolog library
